name: hugo-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.81.0" # hugo 版本
          extended: true

      - name: Build
        run: cd blog-hugo && hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: chiaowei-weng/blog-hugo
          publish_branch: gh-pages
          publish_dir: ./blog-hugo/public
          commit_message: ${{ github.event.head_commit.message }}
